# Generated by Django 4.2.16 on 2026-04-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('profile_type', models.CharField(blank=True, choices=[('nature_explorer', 'Explorateur Nature'), ('urban_luxury', 'Urbain Luxe'), ('budget_family', 'Famille Budget'), ('adventure_seeker', "Chercheur d'Aventures"), ('cultural_nomad', 'Nomade Culturel'), ('beach_relaxer', 'Détente Plage'), ('mountain_retreat', 'Retraite Montagne'), ('city_business', 'Business Urbain')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'psychological_tests',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='properties.property')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score'],
            },
        ),
    ]
