# Generated by Django 4.2.16 on 2026-04-13 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologicaltest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychological_test', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'property')},
        ),
    ]
